#ip_adres = '192.168.1.1'

ip_adres = input('Geef ip-adres in: ')
print('Ip-adres is:' + ip_adres)
print(type(ip_adres))
ip_adres = ip_adres.split(".")
print(ip_adres)
getal_1 = int(ip_adres[0])
print(getal_1)
getal_2 = int(ip_adres[1])
print(getal_2)
getal_3 = int(ip_adres[2])
print(getal_3)
getal_4 = int(ip_adres[3])
print(getal_4)
dec_getal_1 = getal_1 * (256 **3)
print (dec_getal_1)
dec_getal_2 = getal_2 * (256 **2)
print (dec_getal_2)
dec_getal_3 = getal_3 * (256 **1)
print (dec_getal_3)
dec_getal_4 = getal_4 * (256 **0)
print (dec_getal_4)

ip_decimaal = print(dec_getal_1 + dec_getal_2 + dec_getal_3 + dec_getal_4)
